server {
	listen 8080;	#Choose the port and host of each ’server’.	#listen [::]:443 ssl;
	#server_names  or not
    body_size();	#Limit client body size.

	#Definir el directorio raíz de tu sitio
    root /var/www/ejemplo.com;
    
	#Definir páginas de error personalizadas para errores específicos
    error_page 404 /custom_404.html;
	# Configurar la ubicación de las páginas de error personalizadas
	location = /custom_404.html {
		root /var/www/errors;  #Ubicacion del archivo
		internal;              #Indica que no se puede acceder directamente a esta ubicación
	}

	#Página de inicio predeterminada predeterminada 
	location / {
		try_files $uri $uri/ =404;  #Intenta acceder al archivo, devuelve error 404 si no existe
		# ...
	}
}

server     {
	listen 80;
	server_name api.ejemplo.com;  # Este servidor responde a api.ejemplo.com

	location / {
		return 200 "Este es el servidor para el subdominio api.ejemplo.com.\n";
	}
}