server {
  listen 127.0.0.1:8001;              # listening port, mandatory parameter & host or 127.0.0.1 by default
  server_name test;                   # specify server_name, need to be added into /etc/hosts to work
  error_page 404 /error/404.html;     # default error page
  error_page 500 /error/500.html;
  client_max_body_size 1024;          # max request body size in bytes
  root /site_root;                        # root folder of site directory, full or relative path, mandatory parameter
  index index.html;                   # default page when requesting a directory, index.html by default

  location / {
      allow_methods  DELETE POST GET;
      autoindex off;
  }

  location /docs/fusion_web {                   
      root ./;          # root folder of the location, if not specified, taken from the server. 
                                      # EX: - URI /tours           --> docs/fusion_web/tours
                                      #     - URI /tours/page.html --> docs/fusion_web/tours/page.html 
      autoindex on;                   # turn on/off directory listing
      allow_methods POST GET;         # allowed methods in location, GET only by default
      index index.html;               # default page when requesting a directory, copies root index by default
      return /abc/index1.html;        # redirection
      alias  /docs/fusion_web;        # replaces location part of URI. 
                                      # EX: - URI /tours           --> docs/fusion_web
                                      #     - URI /tours/page.html --> docs/fusion_web/page.html 
  }

  location /cgi-bin {
      root /algo;                              # cgi-bin location, mandatory parameter
      index calculator.py;
      cgi_path /usr/bin/python3 /bin/bash;  # location of interpreters installed on the current system, mandatory parameter
      cgi_ext .py .sh;                      # extensions for executable files, mandatory parameter
  }
}

server {
    listen 127.0.0.1:8002;
	server_name localhost;
    root /site_root;
    client_max_body_size 3000000;
	index index.html;
    error_page 404 /error/404.html;

    location / {
        allow_methods  DELETE POST GET;
        autoindex off;
    }

    location /cgi-bin {
        root /algo;
        allow_methods GET POST DELETE;
        index time.py;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}